spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          #git仓库 在公司里，配置存储仓库  单独的
          uri: https://github.com/wenjiaquan/Spring-Cloud.git
            #检索目录
          search-paths:
            - configs
          #默认拉取的配置分支
          default-label: master
            #从那个分支去拉取配置文件
        label: cloud-config
server:
  port: 8888